### ISSUE TITLE
Revoked cetificate

### ISSUE THREAD

**Issue by Psychokiller1888** [Flyspray/flyspray.github.io#8]
Nothing to do with flyspray, but flyspray webpage includes references to thevelozgroup.com and Avast returns me that the certificate was revoked and thus the page blocked...

**Comment by peterdd** [comment]
Why did you closed? Check http://www.flyspray.org/devel/team/ with current firefox 36.0.1 to see. No Image of you, no link to your company working..

**Comment by Psychokiller1888** [comment]
Weird, because it wasn't working on chrome for me when I reported it, but now it's ok again for me

**Comment by Psychokiller1888** [comment]
True, Avast still warns me when going to flyspray.org

**Comment by peterdd** [comment]
tested yesterday with chrome - no warning of revoked certificate
tested yesterday with firefox  - warning of revoked certificate

maybe firefox is more strict in validating?

**Comment by peterdd** [comment]
I wanted to share the link to the bugtracker via facebook chat, it was denied by facebook, tried several variations like without or with https.

So this is a serious case!

The page cert tells verified by  COMODO CA Limited, but COMODO is not the best cert. (in polite words)
